### ISSUE TITLE
Contributing documentation

### ISSUE THREAD

**Issue by myusko** [Neoteroi/BlackSheep#113]
Hi @RobertoPrevato and thank you for a cool framework.

Probably for new contributors, would be cool to see **contribution** documentation in place.

- how to contribute
- what type of style we should follow
- how to set up a development environment
- how we should name branches
- ...etc..

Does this make sense?

**Comment by kun1996** [comment]
I couldn't agree more

**Comment by RobertoPrevato** [comment]
You have a good point, I will write something about this subject as soon as possible.
I was planning to write something on this subject, I postponed simply because I was working on other things.

I will describe these things in the upcoming weekend (in two days' time) 👍🏼

**Comment by myusko** [comment]
Sure, take your time! I believe the community going to appreciate it.

**Comment by RobertoPrevato** [comment]
Hi @kun1996 @myusko 
I just deployed an update to the documentation, which includes a new section about contributing.

Can you please check it? If you have recommendations to improve it, please let me know. https://www.neoteroi.dev/blacksheep/contributing/

Side note: currently the documentation is in a [public repository in Azure DevOps](https://dev.azure.com/robertoprevato/BlackSheep/_git/Docs). I will migrate it to a dedicated repository in GitHub, when I have a free moment to re-write GitHub Workflows that do the same things of the current Azure Pipelines.

**Comment by myusko** [comment]
@RobertoPrevato I definitely love it :heart: also, probably in the future we can consider [isort](https://github.com/PyCQA/isort) and [mypy](https://github.com/python/mypy) 
I have already run the mypy cheks and looks like if we decided to use `mypy` we will have some work in order to make `mypy` happy

**Comment by RobertoPrevato** [comment]
I didn't know about `isort`, thanks for the heads up! Speaking about `mypy`, I have experience with it: last year I had the pleasure to work for EdgeDB for several months, and the first task they asked me to help with, was exactly refactoring EdgeDB's source code to make MyPy happy and achieve 100% type coverage.

Here's my opinion at the light of that experience:
1. I find MyPy extremely useful during development, to find _obvious_ mistakes (I use both MyPy and pylance)
1. I think that some things that Python allow, and were allowed many years before people in the Python community started being sensitive about type properness, contribute to the beauty of the language, and I don't care if `MyPy` complains about them.
1. I know C# pretty well, and if I cared about type correctness to that degree to make my code 100% MyPy compliant, I would surely code in C# rather than in Python.

**Comment by myusko** [comment]
Thanks for sharing your experience, that's really interesting:)

Regarding `isort` I love it and trying to use in each my project, probably we can find some useful extensions for the **flake8** https://github.com/DmytroLitvinov/awesome-flake8-extensions and integrate into **BlackSheep**.

**Comment by RobertoPrevato** [comment]
Closing this issue now, if any more recommendation will arrive for documenting how to contribute to BlackSheep, we can improve later the documentation. 😄
