### ISSUE TITLE
Clean up tests

### ISSUE THREAD

**Issue by myusko** [Neoteroi/BlackSheep#114]
Hey @RobertoPrevato per our discussion, would be cool to make our tests, a bit cleaner.

- Use **pytest fixtures** if the code is repeating
- Remove unused imports

And if you have some thoughts, what we should definitely refactor in our tests, please share it :smile: I'd happy to clean up tests.

P.S in the core functionality, I also saw unused imports, etc, in the future, we should clean up it as well.

**Comment by RobertoPrevato** [comment]
Perfect! 😄 
I am not sure if unused imports in the core functionality are not simply those done to enable importing and shorten the import path for users of the library. Because I am using `flake8` to detect this kind of things and this is also validated during the [CI build](https://github.com/Neoteroi/BlackSheep/blob/main/.github/workflows/main.yml) (if you search for `flake8` you will see it there).

As we discussed yesterday, in the weekend I will write documentation on contributions and to describe the development environment I've been using so far (e.g. `black` formatter, `flake8`).

**Comment by myusko** [comment]
@RobertoPrevato Yeah, regarding unused imports, sorry this is my bad, I was sure that I've seen it in the code :smile:

**Comment by myusko** [comment]
The Issue was fixed in #119 and #115

Reopen it, if we will need to do some clean-up in the tests/core functionality in the future.
