### ISSUE TITLE
Typo in the documentation(middleware)

### ISSUE THREAD

**Issue by myusko** [Neoteroi/BlackSheep#128]
Hey @RobertoPrevato in the middlewares documentation we should fix code-example
https://www.neoteroi.dev/blacksheep/middlewares/

Handler `home` should receive `request` argument.

**Comment by RobertoPrevato** [comment]
Hi @myusko, there is no typo. :D
The example works thanks to the normalization of request handlers! This is one of the most complex features I added to the framework (ASP.NET Core behaves in the same way, so I was inspired by it).

Please try it, you'll see that it works.

![image](https://user-images.githubusercontent.com/2576032/117783381-c48b9600-b242-11eb-87d0-46b0567345a0.png)

This thing is described earlier in the documentation, here: https://www.neoteroi.dev/blacksheep/request-handlers/#request-handler-normalization

You don't always need to access the request object, and the framework encourages leveraging the normalization of request handlers without accessing the request object directly, because it enables accurate generation of OpenAPI Docs.
It is still possible to access the request directly and document by hand parameters, request body, response types.

PS. Your first contribution is [on PyPi](https://pypi.org/project/blacksheep/) available with `1.0.5` (exceptions handlers defined using the decorator you added).
