### ISSUE TITLE
Right way to use Postgres

### ISSUE THREAD

**Issue by david-lint** [Neoteroi/BlackSheep#134]
Sorry for disturbing, I'm new with python. 
Could you please show me a sample of right way to connect 🐑 with a postgres.

Thank you!

**Comment by RobertoPrevato** [comment]
Hi @david-lint
Tomorrow I will publish a project template featuring one of the possible good ways to use Postgres. There is not a single "right way", because some people like to use SQL dbs with an ORM, some people prefer not to use ORMs; some prefer DB first approach, others code first.

I personally prefer code first approach, and I like both using ORMs and using db drivers directly.

The template I will publish tomorrow enables the following things:
* database migrations applied automatically by continuous delivery pipelines (implemented using GitHub workflows), using Alembic
* collection of telemetries to keep a log of how much time queries take to complete (using OpenCensus and Azure Application Insights), to get reports like the following:
![image](https://user-images.githubusercontent.com/2576032/118363908-c208a380-b596-11eb-869b-1d1b70016c7c.png)

* business logic and front-end layer are abstracted from the code that interacts with Postgres (this, in my opinion, is a fundamental feature)

Please let me come back to this issue tomorrow, or on Monday, to elaborate a bit on the project template I will publish.

**Comment by RobertoPrevato** [comment]
Note that the telemetries are collected using OpenCensus, therefore the same principle I will share is valid and applies to other scenarios (even without Azure Application Insights).

**Comment by RobertoPrevato** [comment]
Hi @david-lint,
As I promised, yesterday I started publishing the demo project I am working on. It is still a work in progress, but you can already see an example of using PostgreSQL with BlackSheep.

I described it here: https://github.com/Neoteroi/BlackSheep/discussions/130#discussioncomment-746498

Hope this helps. 🙂

**Comment by myusko** [comment]
Also, to add a few more words to the @RobertoPrevato 's answer, you can consider the MVC pattern for your applications.

Regarding async libraries, I can suggest the https://github.com/encode/databases package

**Comment by RobertoPrevato** [comment]
Hi @david-lint 
Today I published a library to simplify the integration with SQLAlchemy -> https://pypi.org/project/blacksheep-sqlalchemy/

For now it's basic, as it registers the necessary services to:
* registers services to the DI container so that db connection, sessions, and the engine, so that they can be injected to request handlers (or dependent services) - [there is a full example here](https://github.com/Neoteroi/BlackSheep-SQLAlchemy/blob/main/tests/app.py)
* dispose of the SQLAlchemy engine when the application stops

The demo project I described a few days ago is something advanced, handling more details, but if you need to get started with something lighter, you can take a look at the new repository. It also includes integration for ORM Sessions, that can be preferred by many over using a driver directly.

Closing this ticket now, since much information has been provided on this subject. Please let me know if you have any recommendation on integrations with PostgreSQL or other RDBMS.
