### ISSUE TITLE
hypercorn: TypeError: Argument 'headers' has incorrect type (expected list, got Headers)

### ISSUE THREAD

**Issue by romikforest** [Neoteroi/BlackSheep#153]
I wrote a simple application and it works nice with uvicorn. But if I try to use hypercorn it crushes with TypeError: Argument 'headers' has incorrect type (expected list, got Headers)

Error in ASGI Framework
Traceback (most recent call last):
  File "/Users/romik/Work/swo/Release3/kbtest3/venv/lib/python3.9/site-packages/hypercorn/asyncio/context.py", line 39, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "/Users/romik/Work/swo/Release3/kbtest3/venv/lib/python3.9/site-packages/hypercorn/utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "/Users/romik/Work/swo/Release3/kbtest3/venv/lib/python3.9/site-packages/blacksheep/server/application.py", line 595, in __call__
    request = Request.incoming(
TypeError: Argument 'headers' has incorrect type (expected list, got Headers)

MacOS 11.3.1
Python 3.9.4
hypercorn (0.11.2)
blacksheep-1.0.5-cp39-cp39-macosx_10_14_x86_64.whl

**Comment by RobertoPrevato** [comment]
@romikforest thank you for this bug report. I should improve the integration tests to test also other kinds of ASGI frameworks. I will look into this soon. By the way I am a bit surprised because `headers` from the ASGI frameworks should look the same (probably they are equivalent in Python, but not for Cython).

**Comment by RobertoPrevato** [comment]
I reproduced the issue and I confirm that Hypercorn handles its own type of Headers, compatible with a list of tuples in Python, but of course not liked by Cython. As a side note, several months ago I tested with Hypercorn and daphne and it was working, this means that in the past Hypercorn was handling headers in the exact same way as uvicorn.

![image](https://user-images.githubusercontent.com/2576032/120095946-0c5a5a80-c129-11eb-8db3-7570e1920252.png)

I just fixed the bug and I will ship a new version of the framework in PyPi - I prefer to fix immediately this kind of bug since build and deployment to PyPi is automated anyway and it's not painful to release. I keep the preparation of integration tests for Hypercorn and daphne for later.

**Comment by RobertoPrevato** [comment]
Hi @romikforest,
I just released [v1.0.6](https://pypi.org/project/blacksheep/), the issue has been resolved. I also modified the integration tests and GitHub Actions to test Hypercorn (maybe I will add daphne in the future). Thanks again for the heads up!
