### ISSUE TITLE
Piccolo ORM

### ISSUE THREAD

**Issue by Anonymous1313-tech** [Neoteroi/BlackSheep#163]
I think if Piccolo ORM was integrated into BlackSheep it would be awesome! because that orm is async and has understandable python syntax, admin, migration and api tools. https://github.com/piccolo-orm/piccolo

**Comment by myusko** [comment]
Hi @Anonymous1313-tech 

This is a good idea to consider it as a standalone extension for the BlackSheep, thanks for the suggestion.

Thanks,
Mykhailo

**Comment by RobertoPrevato** [comment]
Daniel, I just tried the command to bootstrap an application, and I love it!
As I wrote a couple of days ago,  `piccolo orm` looks great to me, I like its fluent code api very much.

> It seems fairly easy to get Piccolo and BlackSheep working together, so might not need a special extension.

I agree with you. With SQLAlchemy it was different because it requires handling ORM sessions, or db connections, so having them configured in the DI container makes sense, but Piccolo takes things under a different point of view.

> I'm not an expert with BlackSheep, so if someone could give piccolo asgi new a go, and let me know if the outputted code is idiomatic BlackSheep code, I'd appreciate it :)

Yes, it looks perfect to me. 👍🏼 I see that BlackSheep needs to be improved to handle better the Pydantic models, for example right now it cannot generate OpenAPI Documentation for specific types like `ConstrainedStrValue`

**Comment by dantownsend** [comment]
@RobertoPrevato Great, thanks for checking that for me.

**Comment by RobertoPrevato** [comment]
I just published `v1.0.7`, which adds support for special types from `pydantic`, which are also used by `piccolo`.

@Anonymous1313-tech I will close this issue, since as Daniel said, it seems there is no need for a dedicated plugin.

As a side note, now the OpenAPI Documentation generated for the scaffold project in [piccolo](https://github.com/piccolo-orm/piccolo) is as follows (it should be right, except for the `home` "/" - OAD is generally only used for API methods, not for methods that return HTML, so no big issue 🙂 - I will make a tiny PR to ignore the home endpoint):

```yaml
openapi: 3.0.3
info:
    title: Example API
    version: 0.0.1
paths:
    /:
        get:
            responses: {}
            operationId: home
    /tasks:
        get:
            responses:
                '200':
                    description: Success response
                    content:
                        application/json:
                            schema:
                                type: array
                                nullable: false
                                items:
                                    $ref: '#/components/schemas/TaskModelOut'
            operationId: tasks
        post:
            responses:
                '200':
                    description: Success response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskModelOut'
            operationId: create_task
            parameters: []
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskModelIn'
                required: true
    /tasks/{task_id}:
        put:
            responses:
                '200':
                    description: Success response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskModelOut'
            operationId: put_task
            parameters:
            -   name: task_id
                in: path
                schema:
                    type: integer
                    format: int64
                    nullable: false
                description: ''
                required: true
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskModelIn'
                required: true
        delete:
            responses: {}
            operationId: delete_task
            parameters:
            -   name: task_id
                in: path
                schema:
                    type: integer
                    format: int64
                    nullable: false
                description: ''
                required: true
        patch:
            responses:
                '200':
                    description: Success response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskModelOut'
            operationId: patch_task
            parameters:
            -   name: task_id
                in: path
                schema:
                    type: integer
                    format: int64
                    nullable: false
                description: ''
                required: true
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskModelPartial'
                required: true
servers: []
components:
    schemas:
        TaskModelOut:
            type: object
            required:
            - id
            - name
            - completed
            properties:
                id:
                    type: integer
                    format: int64
                    nullable: true
                name:
                    type: string
                    maxLength: 255
                    nullable: true
                completed:
                    type: boolean
                    nullable: false
        TaskModelIn:
            type: object
            required:
            - name
            - completed
            properties:
                name:
                    type: string
                    maxLength: 255
                    nullable: true
                completed:
                    type: boolean
                    nullable: false
        TaskModelPartial:
            type: object
            required:
            - name
            - completed
            properties:
                name:
                    type: string
                    maxLength: 255
                    nullable: true
                completed:
                    type: boolean
                    nullable: false
```

**Comment by RobertoPrevato** [comment]
-- actually, reopening to keep in mind we need to update the documentation to reference `piccolo-orm`.

**Comment by RobertoPrevato** [comment]
Referenced in the documentation here https://github.com/piccolo-orm/piccolo

**Comment by dantownsend** [comment]
@RobertoPrevato Awesome, thanks for this.

**Comment by virajkanwade** [comment]
Hi @RobertoPrevato 
Sorry to comment on a closed ticket, but I think we should still have an extension.

See flask-sqlalchemy for example. https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/
you can just write `db = SqlAlchemy(app)` and it automatically loads the connection settings from the config and initializes all engine setup.
Similarly, you have blacksheep_sqlalchemy , `use_sqlalchemy(app, connection_string="<CONNECTION_STRING>")`

Maybe you could make essentials-configuration an integral part of blacksheep core for config management similar to flask's `app.CONFIG`.

All said and done, right now with the way blacksheep and piccolo integate, we need to maintain 2 different sets of configs.

Having a inbuilt config manager and an extension which internally configures piccolo from the config would be a great feature.

**Comment by RobertoPrevato** [comment]
Hi @virajkanwade 
Regarding `essentials-configuration`, I think you are right and it's time to include it in the web framework to provide some functionalities out of the box (a common way to manage app settings and a configuration root). I didn't do this at the beginning for a couple of reasons, the main being that I created the `essentials-configuration` package much later.

As a side note, I would like to improve `essentials-configuration` to support typed configuration objects - currently it is designed with dynamism in mind and doesn't validate the shape of settings objects. 

When we speak about SQLAlchemy, I maintain a plugin for it, I am not sure if you saw it: https://github.com/Neoteroi/BlackSheep-SQLAlchemy

For Piccolo ORM, since it is by itself an ASGI app that can be mounted in other applications, and more importantly because of lack of time on my side (I already maintain 20 projects inside the Neoteroi organization + a few on my first GitHub account - all for passion and in my private time), I don't plan at the moment to maintain a dedicated package for it.

**Comment by virajkanwade** [comment]
@RobertoPrevato thanks

Altough brought one more question, "more importantly because of lack of time on my side (I already maintain 20 projects inside the Neoteroi organization + a few on my first GitHub account - all for passion and in my private time)" Is blacksheep something that will be officially maintained or is it one of your personal projects?

Thanks
