### ISSUE TITLE
ORJSON fail to return Response - bytes instead of str

### ISSUE THREAD

**Issue by Joffreybvn** [Neoteroi/BlackSheep#192]
Hello,
First, I really like what you do with this library !

When I use ORJSON as a plugin, like stated [in the documentation](https://www.neoteroi.dev/blacksheep/settings/), calling `json(data, status=200)` produces this error:
```
AttributeError: 'bytes' object has no attribute 'encode'
```
This is because python's json.dumps() [returns a string](https://docs.python.org/3/library/json.html#json.dumps), while orjson.dumps() [returns a bytes](https://github.com/ijl/orjson#quickstart). Thus, calling `.encode("utf8")` on this bytes raise an error.

Here is a suggestion of correction: https://github.com/Neoteroi/BlackSheep/pull/191

**Comment by RobertoPrevato** [comment]
Hi @Joffreybvn,
Thank You for your kind words and for reporting this bug, this is primarily a mistake in the documentation. I appreciate your proposal, but I would prefer to not add another function to handle JSON responses. 

Even though this originated from a mistake in the documentation, I'm considering to change the "plugin" dumps function (the one that currently uses the built-in `json` package) to be a function that returns bytes instead of str - after all ultimately `bytes` get written to the TCP transport, so we could embrace `orjson`'s point of view in this.

**Comment by RobertoPrevato** [comment]
After pondering about this, I decided to:
* update the [documentation](https://www.neoteroi.dev/blacksheep/settings/#example-using-orjson) with correct instructions and more information - this specific issue is fixed
* to **not** modify the current BlackSheep code to add and `isinstance(dumps_result, bytes)` in the function responsible of JSON serialization because this would reduce the performance of that method by 6% (verified using ipython)
* to **not** modify the current BlackSheep code API to expect a `dumps` function that returns `bytes`, because this is something specific to `orjson` (different than what the built-in `json`, `UltraJSON`, `RapidJSON`, `fast-json`, and all other libraries I know from other programming languages do)

Anyway I explained in the documentation how to avoid the performance fee of the superfluous `decode -> encode` passage for users using `orjson` who want to avoid that fee (so that the result of `orjson.dumps` is passed directly as response content).

Thank You again for reporting this issue!

**Comment by RobertoPrevato** [comment]
Hi @mohd-akram,
If you read carefully the comment I wrote when closing this issue, I decided to correct the error in the documentation and not change the code. Please find the documentation with the updated example [here](https://www.neoteroi.dev/blacksheep/settings/#example-using-orjson).

**Comment by mohd-akram** [comment]
Ah, sorry, I didn't read properly. Thank you and thanks for this cool framework.

**Comment by RobertoPrevato** [comment]
Thank You!
