### ISSUE TITLE
using static files

### ISSUE THREAD

**Issue by Trigger7701** [Neoteroi/BlackSheep#201]
Hello Roberto, I can't use static files everywhere in template, because when I use that I have to put statics every path. Can I use static files as absolute one directory like Django .

**Comment by RobertoPrevato** [comment]
Hi!
I am not sure I understand your question. BlackSheep supports configuring folders for static files using absolute paths, and even paths outside of the CWD of the web application. Files are served dynamically, so it's sufficient to configure the parent folder of public files that can be served.

The example [here](https://github.com/Neoteroi/BlackSheepMVC/blob/main/app/program.py) shows how to configure a folder for static files using a relative path - the path must be relative to the CWD of the web app.

Can you please show a code example of what you tried and what you cannot achieve?

**Comment by Trigger7701** [comment]
Thanks so much for the reply! 
I put statics in this folder: "app/static/mystatic/", and it works for the "127.0.0.1:8000/users/" , but it doesn't work in "127.0.0.1:8000/users/edit" because  "users" is added to the static address.
STATIC:
127.0.0.1:8000/.../some.css is working, but
127.0.0.1:8000/users/.../some.css is not working.
Thanks for your answer!

**Comment by Trigger7701** [comment]
I want to keep all the statics in one folder

**Comment by RobertoPrevato** [comment]
Ah, now I understand. This is not an issue in the web framework, it depends on how you are linking static files on the HTML documents you serve to the client.

This is because of how browsers work. For example, if you have a relative link to a favicon in your HTML, say:

```html
<link rel="icon" href="./favicon.ico" type="image/x-icon" />
```

The problem you describe will happen for documents served at sub-paths.

If you have an absolute link to a favicon, the problem doesn't happen (note "/" instead of "./"):

```html
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
```

Most web frameworks have a dedicated function to render relative paths to static files, depending on the path of the current request (e.g. ASP.NET Core has "~/" for this). Anyway, this is not really a bug - if you know that your files are at "/styles/example.css" then you can simply use absolute URLs when configuring your views instead of relative paths.

**Comment by Trigger7701** [comment]
Yes, It's not problem, I'm sorry. I just wanted to ask. I  understood you. But when I use Django it's easy {% static '.../some.css' %}, and I want to use this method in your framework. How can I that.

**Comment by RobertoPrevato** [comment]
Right now there is no built-in handling for this. It is possible to configure a global helper function in the Jinja2 environment that is set on the application by `use_templates` function, changing the [environment globals](https://jinja.palletsprojects.com/en/3.0.x/api/?highlight=globals%20update#the-global-namespace). Flask has something [similar with Jinja2](https://stackoverflow.com/questions/42064874/jinja2-link-to-static-files).

Thanks for opening this issue, this feature could be added to the framework.

**Comment by Trigger7701** [comment]
Thank you so much for taking the time to do this and for helping!

**Comment by RobertoPrevato** [comment]
Thank You for your kind words! I will try to add this feature to the next version that gets published to `pypi`. By the way, these days I am working to add an important feature to the framework: built-in support for OpenID Connect, which will make it very simple to integrate with identity provider services such as `Auth0`, `Okta`, `Azure Active Directory`, and `Azure Active Directory B2C`. 

Contextually I am also adding a middleware to handle trusted hosts and forward headers, and some other niceties.
