### ISSUE TITLE
how to pass dynamic params to services?

### ISSUE THREAD

**Issue by 56907dzq** [Neoteroi/BlackSheep#265]
##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

Can service add  dynamic params?

for example:

I register ClientSession to app.service,

cam I specify the request_timeout and connection_timeout?

or Timeout could be overridden for a request like ClientSession.get()?

**🚀 Feature Request**

**Comment by RobertoPrevato** [comment]
Hi @56907dzq 
I apologize for  replying so late. 🙇🏼 

The dependency injection library supports resolving services that require dynamic parameters using factories.
A common real-life example would be a context object that provides a "correlation id" to a whole scope (in this case, to a web request), as [described here](https://www.neoteroi.dev/blacksheep/dependency-injection/#example-implement-a-request-context).

In the case of the `ClientSession`, if you wish to configure the `request_timeout` and `connection_timeout`, you can do it once, configuring a singleton instance. Please note that, since the `ClientSession` handles HTTP connection pooling out of the box, it is necessary to instantiate it when the application starts, and dispose it (i.e. close the connections) when the application stops.

In the following example, a `ClientSession` is registered at application start, and used to obtain the HTML of https://docs.python.org/3/ and serve it as plain text.
 
```python
from blacksheep import Application
from blacksheep.client import ClientSession


app = Application(show_error_details=True)


async def create_client(app: Application):
    app.services.add_instance(ClientSession(
        connection_timeout=120
        request_timeout=120
    ))

async def dispose_client(app: Application):
    http_client = app.service_provider[ClientSession]
    await http_client.dispose()


app.on_start += create_client
app.on_stop += dispose_client


@app.route("/")
async def home(http_client: ClientSession):
    response = await http_client.get("https://docs.python.org/3/")
    return await response.text()
```

Specifying timeouts for single web requests is not supported, I am not sure if this is a feature that would be often needed.

**Comment by 56907dzq** [comment]
hi,@RobertoPrevato
Replying so late is doesn't matter.

Then I think specify timeouts for single web requests's ability is necessary, it is not  Depend on often needed but vital.
Why? Look at other package.
In sync, look at requests, it is very popular,it has this capability.
In async, look at aiohttp,it use like the following example:

![image](https://user-images.githubusercontent.com/45482484/174697552-69269be7-9b19-42cf-a4c4-c6ac78ec5b8a.png)

By the way, ClientSession instance doesn't have dispose method, the correct close method is close
