### ISSUE TITLE
Router blueprint

### ISSUE THREAD

**Issue by Kokoserver** [Neoteroi/BlackSheep#272]
##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

**🚀 Feature Request**
i don't know, though have tried to check, but i don't know if there is anything like blueprint like of flask or Router like of Fastapi, will really make sense, rather than creating new app instances and mounting it can be really costly.

Thanks for blacksheep

**Comment by RobertoPrevato** [comment]
Hi @Kokoserver 
Sorry for replying late, in the last days I dedicated time to [another open source thing](https://www.neoteroi.dev/mkdocs-plugins/) (will also be useful for BlackSheep).

And thank you for your kind words!

Right now the word "BluePrint" is not used in BlackSheep, but this doesn't mean that the framework lacks features that are equivalent to BluePrints as they are presented in the FastAPI documentation.

Note that even FastAPI doesn't use the word "BluePrint" in its source code. They use this word in the documentation because it's familiar for people who used Flask. ([The note at the top of the page](https://fastapi.tiangolo.com/tutorial/bigger-applications/): _If you come from Flask, this would be the equivalent of Flask's Blueprints._).

For example you can define a `Controller` class with base path having very similar features (modularization in different files, own dependencies resolved by dependency injection, base route, automatic tags when generating OpenAPI Documentation).

See for example:  

- [Controller route](https://github.com/Neoteroi/BlackSheep/blob/9fe7d66baf13456e3725f66f41cbc961285a8e2d/blacksheep/server/controllers.py#L94)
- [APIController](https://github.com/Neoteroi/BlackSheep/blob/9fe7d66baf13456e3725f66f41cbc961285a8e2d/blacksheep/server/controllers.py#L389) - which not only handles base paths, also versioning potentially
- How the `Torino` demo project is structured ([controllers](https://github.com/Neoteroi/Torino/tree/dev/server/app/controllers))

```python
class AlbumsController(ApiController):
    def __init__(self, manager: AlbumsHandler) -> None:
        super().__init__()

        self.manager = manager

    @classmethod
    def class_name(cls) -> str:
        return "albums"

    @get("/")
    async def get_albums(self) -> List[Album]:
        """
        Gets the list of albums configured in the system.
        """
        return await self.manager.get_albums()

    @get("/:album_id")
    async def get_album_details(self, album_id: UUID) -> Album:
        """
        Gets details about an album, by its id.
        """
        return await self.manager.get_album(album_id)

    @auth(Roles.ADMIN)
    @post("/:album_id")
    async def update_album(self, album_id: UUID, data: UpdateAlbumInput) -> Album:
        """
        Updates an album by id, with the given input.
        """
        return await self.manager.update_album(data)

```

The handled routes are actually:

- "/api/albums/"
- "/api/albums/{{album_id}}"

It would be even possible to pack controllers in dedicated Python packages, for more complex scenarios (example: having a library with common endpoints to handle OAuth endpoints).

**Comment by Kokoserver** [comment]
Thanks alot

**Comment by RobertoPrevato** [comment]
I reopen this issue because the documentation can be improved. 😃
