### ISSUE TITLE
Jinja helpers

### ISSUE THREAD

**Issue by madgagarin** [Neoteroi/BlackSheep#273]
##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

**🚀 Feature Request**
Hello! It would be great to see global jinja helpers (like request).
Adding the same method to each request is not rational. Perhaps there is another already implemented method?
Regards!

**Comment by RobertoPrevato** [comment]
Hi @madgagarin 
Sorry for replying late, in the last couple of days I dedicated time to [another open source thing](https://www.neoteroi.dev/mkdocs-plugins/) (always related to my projects).

BlackSheep uses Jinja2 internally and supports adding Jinja helpers. But thanks for asking because I see the feature is not well documented right now, and is not typing friendly, so it can be improved.

An example to configure a custom Jinja helper, for example using globals:

```
.
├── app
│   ├── __init__.py
│   └── views
│       └── index.html
└── server.py
```

```python
# server.py
from blacksheep import Application
from blacksheep.server.templating import use_templates
from jinja2 import PackageLoader, Environment

app = Application(show_error_details=True)

view = use_templates(app, PackageLoader("app", "views"))


def example():
    return "This is an example"


app.templates_environment.globals.update({"my_function": example})


@app.route("/")
async def home():
    return view("index.html", {})

```

```html
# index.html
<p>Hello, World!</p>
{{ my_function() }}
```

Result:

```
<p>Hello, World!</p>

This is an example
```

In the same way, it's possible to [configure filters](https://jinja.palletsprojects.com/en/3.1.x/api/#custom-filters).
