### ISSUE TITLE
What about kloop

### ISSUE THREAD

**Issue by yxlwfds** [Neoteroi/BlackSheep#280]
[##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

**🚀 Feature Request**
](https://github.com/fantix/kloop) kLoop is an implementation of the Python [asyncio](https://docs.python.org/3/library/asyncio.html) event loop written in [Cython](https://cython.org/), using [io_uring](https://unixism.net/loti/what_is_io_uring.html) and [kTLS](https://www.kernel.org/doc/html/latest/networking/tls-offload.html) features of the Linux kernel, therefore called k(ernel)Loop.

**Comment by RobertoPrevato** [comment]
Hi @yxlwfds,
Thanks for the heads up. `kloop` looks very interesting, and knowing about the contributions from fantix, I'm sure it can be a promising replacement for `uvloop`.

Right now `blacksheep` operates at an higher level of abstraction: since it was made compatible (and dependent) on ASGI, this library is no more concerned with handling event loop and processes for the HTTP Server part. Therefore this issue is off topic: its place is on ASGI servers (`uvicorn`, `hypercorn`, etc.).

As a side note, when I started blacksheep, it included an implementation of HTTP Server. If I had the time, I would like to still maintain one, but it's too much work to be done for passion during unpaid hours.
