### ISSUE TITLE
Client connection pool in the life cycle of ClientSession

### ISSUE THREAD

**Issue by yangbo1024** [Neoteroi/BlackSheep#302]
##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

**🚀 Feature Request**
It seems that by default, the access to same url and port is cached to the global connection pool, which confuses the concept of ClientSession. It is much more convenient to keep the life cycle following the session, and it is also convenient for the client to control whether the session is released or not, for server load balance.

--thanks.

**Comment by RobertoPrevato** [comment]
Hi,
Thanks for your recommendations. 

> It is much more convenient to keep the life cycle following the session, and it is also convenient for the client to control whether the session is released or not, for server load balance.

With the current library, this thing you describe can be achieved this way (specifying `ClientConnectionPools` for the session):

```python
import asyncio

from blacksheep.client import ClientSession
from blacksheep.client.pool import ClientConnectionPools


async def client_example():
    async with ClientSession(
        pools=ClientConnectionPools(asyncio.get_running_loop())
    ) as client:
        response = await client.get("https://localhost:5000/")

        assert response is not None
        text = await response.text()
        print(text)

asyncio.run(client_example())
```

This way sockets are closed when the session is disposed.

The default works as you described. I was conflicted about this, but I finally opted for this because I have experience in .NET and I know that many .NET developers - even senior - ignore the implications of instantiating a `HttpClient` object (e.g. instantiating one at each web request). Many fall for it, even though it's well documented (e.g. [1](https://learn.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=csharp#static-clients), [2](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net)).

Part of the problem I mention is described in the [second link above](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net).

1. it creates a new connection pool whenever it is instantiated, with possible implications of exhausting sockets in web apps, performance fee of opening new TCP / IP connections
2. additionally, it doesn´t close those TCP / IP connections when it is disposed

This looks like a footgun to me, and rather than recommending everybody to handle the client as singleton, I preferred opting for defaulting to a singleton connection pool if the user doesn't specify one.

**Comment by RobertoPrevato** [comment]
After thinking about this, I decided to follow your recommendation, @yangbo1024, and for version 2 the `ClientSession` will own by default a connection pool and dispose it. I was undecided about it and even left a comment in the code about it. I will make sure that connection pools are well documented, like they are in `Redis` Python library.

Version 1 will continue to behave like it is.

This is already available in the alpha package released with https://github.com/Neoteroi/BlackSheep/releases/tag/v2.0a3

**Comment by yangbo1024** [comment]
So Good!
