### ISSUE TITLE
Trusted Host Middleware

### ISSUE THREAD

**Issue by harpiyacloud** [Neoteroi/BlackSheep#32]
Hi, @RobertoPrevato 

By looking at a few examples, I prepared middleware for the trusted host. There was no problem with my checks. Is the middleware I prepared suitable for your standards? I will try to add www redirect to it. I am trying to understand the your redirect response function.

```
from typing import Sequence, Callable, Awaitable

from blacksheep import Request, Response
from blacksheep.server.responses import text

ENFORCE_DOMAIN_WILDCARD = "Domain wildcard patterns must be like '*.example.com'."


class TrustedHostMiddleware:
    def __init__(
            self,
            allowed_hosts: Sequence[str] = None,
    ) -> None:
        if allowed_hosts is None:
            allowed_hosts = ["*"]

        for pattern in allowed_hosts:
            assert "*" not in pattern[1:], ENFORCE_DOMAIN_WILDCARD
            if pattern.startswith("*") and pattern != "*":
                assert pattern.startswith("*."), ENFORCE_DOMAIN_WILDCARD

        self.allowed_hosts = list(allowed_hosts)
        self.allow_any = "*" in allowed_hosts

    async def __call__(self,
                       request: Request,
                       handler: Callable[[Request], Awaitable[Response]]
                       ) -> Response:
        host = request.headers.get_single(b"host").decode("utf-8").split(":")[0]
        is_valid_host = False
        for pattern in self.allowed_hosts:
            if host == pattern or (
                    pattern.startswith("*") and host.endswith(pattern[1:])
            ):
                is_valid_host = True
                break
        if is_valid_host:
            response = await handler(request)
        else:
            response = text("Invalid host header", status=400)
        return response
```

**Comment by RobertoPrevato** [comment]
Hi @harpiyacloud,
First thing, thank you for the heads up and bringing up this topic. I was ignorant of the security vulnerability of DNS rebinding when a web server is directly exposed to the internet and doesn't validate the host header, or hosted behind a proxy that doesn't restrict host request headers.

I normally host my web applications behind proxies that do such validation (IIS, NGINX, Apache), actually today using cloud services that do it (e.g. Azure App Service Plan); and enforcing HTTPS; this is why I wasn't aware of this security vulnerability.

This is something that deserves documentation, and possibly adding a middleware to the web framework as I think you are recommending?

---
Speaking about your code, I have a few recommendations:
* I would use `@property` for the allowed_hosts; and a setter; to validate the allowed hosts whenever allowed_hosts is set (currently the validation happens only inside the constructor)
* make allow_any a read-only property, since it is computed from allowed_hosts
* extract the portion that validates a host value to a dedicated function

```python
from typing import Awaitable, Callable, List, Optional, Sequence

from blacksheep import Request, Response
from blacksheep.server.responses import text

ENFORCE_DOMAIN_WILDCARD = "Domain wildcard patterns must be like '*.example.com'."


class TrustedHostMiddleware:

    def __init__(
            self,
            allowed_hosts: Sequence[str] = None,
    ) -> None:
        self._allowed_hosts = None
        self.allowed_hosts = allowed_hosts

    @property
    def allow_any(self) -> bool:
        return "*" in self.allowed_hosts

    @property
    def allowed_hosts(self) -> List[str]:
        return self._allowed_hosts

    @allowed_hosts.setter
    def allowed_hosts(self, value: Optional[Sequence[str]] = None) -> None:
        if value:
            self._validate_allowed_hosts(value)
        else:
            value = ["*"]
        self._allowed_hosts = list(value)

    def _validate_allowed_hosts(self, value: Sequence[str]) -> None:
        for pattern in value:
            assert "*" not in pattern[1:], ENFORCE_DOMAIN_WILDCARD
            if pattern.startswith("*") and pattern != "*":
                assert pattern.startswith("*."), ENFORCE_DOMAIN_WILDCARD

    def is_valid_host(self, host: str) -> bool:
        for pattern in self.allowed_hosts:
            if host == pattern or (
                pattern.startswith("*") and host.endswith(pattern[1:])
            ):
                return True
        return False

    async def __call__(self,
                       request: Request,
                       handler: Callable[[Request], Awaitable[Response]]
                       ) -> Response:
        host = request.headers.get_single(b"host").decode("utf-8").split(":")[0]

        if self.is_valid_host(host):
            response = await handler(request)
        else:
            response = text("Invalid host header", status=400)
        return response
```

I would also consider throwing a dedicated exception instead of using `assert` (since assert can be disabled by running python with -O flag; and here it could be more relevant to always throw exception); and handle multiple request `host` headers by returning 400 (with the current code it would result in status 500 since `get_single` throws exception when there is more than one match.

**Comment by harpiyacloud** [comment]
Hi @RobertoPrevato 

Thank you for your answer. I will update the system taking into account your suggestions. Yes, I wanted to make a suggestion. Now all web framework structures support this. For example, django requires this for safety reasons at the product stage. I will use it for the system I am working on. Except for a few shortcomings (for exam. jwt, cors maybe Redis cache), your infrastructure looks better than the others.

**Comment by RobertoPrevato** [comment]
Thanks - I will work on these improvements. If you would like to do a PR for the TrustedHostMiddleware, I will accept it.

In the last weeks I learnt many things about code quality assurance in Python (from very talented people), and I started learning about GitHub Actions / workflows. For example I improved `rodi` to add flake8 validation and to have a build validation workflow for PR in GitHub. I will do the same for BlackSheep. Then I will work on CORS, JWT validation and more improvements.
