### ISSUE TITLE
Is there an ETA on stable v2?

### ISSUE THREAD

**Issue by aabmets** [Neoteroi/BlackSheep#411]
Our team needs to lock in a choice for a backend API framework and currently we are between FastAPI and Blacksheep. We would like to go with Blacksheep version 2, if it reaches stable in the near future. Therefore, is there an approximate known ETA for stable version 2?

**Comment by aabmets** [comment]
Well, it is delightful to see that @RobertoPrevato released [v2.0a11](https://github.com/Neoteroi/BlackSheep/releases/tag/v2.0a11) yesterday, which indicates that he is working on v2.0. I'm hopeful that we'd be able to use stable v2.0 soon! :)

**Comment by RobertoPrevato** [comment]
Hi @aabmets 
Apologies for replying late, I'm very busy at work and at home lately. I plan to release v2 as production stable very soon, the only thing holding me back is that I didn't complete writing all documentation about it. There are several breaking changes compared to v1, and I would like to publish the documentation and migration instructions before making it stable.
I aim at releasing v2 as prod/stable in **October**.

Because I am a single maintainer without funding, unfortunately I have limited time resources for it. But you can trust the project is live and kicking, I am also using it to build non-open source web applications.

**Comment by aabmets** [comment]
@RobertoPrevato Thank you for your hard work! I can't promise anything, but if Blacksheep should become an inseparable component in my employer software, then I'll consider becoming a maintainter for the project, if you're looking one.
