### ISSUE TITLE
Mypy complains when trying to access rodi-specific methods in 2.0

### ISSUE THREAD

**Issue by Klavionik** [Neoteroi/BlackSheep#454]
After updating to 2.0 I noticed there is a warning from PyCharm when accessing attributes like `service_provider`, `services.add_singleton` etc. on the application instance. 

Mypy complains too.
![Screenshot from 2023-12-23 20-17-51](https://github.com/Neoteroi/BlackSheep/assets/56698047/76c645ad-69dd-46e7-bacd-00854c22ab4f)

And while some of these attribute are actually available (like `add_singleton`), others are indeed broken (like `service_provider`). 

That's perfrectly explainable because now Blacksheep supports injecting custom DI providers. I guess it's reasonable to take another step and make the `Application` type a generic on the DI provider type. This will make Blacksheep more developer-friendly. I'm not super fluent in types but something like this should work, I guess:

```python
import rodi
from typing import Generic, TypeVar

DependencyProvider = TypeVar("DependencyProvider", covariant=rodi.ContainerProtocol)


class Application(Generic[DependencyProvider]):
    def __init__(services: Optional[DependencyProvider] = None):
        if services if None:
            services = rodi.Container()
        self._services = cast(DependencyProvider, services)

    @property
    def services() -> DependencyProvider:
        return self._services
```

Then, it will work like this:
```python
from blacksheep import Application
from typing import TypeAlias

class MyDI:
    def typehinted() -> bool:
        return True

app = Application[MyDI](services=MyDI())
# 
```

This probably has a downside - if we're ok with using the default provider, which is rodi, we still have to annotate the `Application`, like `app = Application[rodi.Container]()`. I'm not sure if there's a workaround.

**Comment by RobertoPrevato** [comment]
I don't like the idea of using a generic type for this scenario because I like the Application class to be abstracted away from the dependency injection Container: all it needs to know is that the container can be used to register and resolve types, nothing more. 
If you only use singletons and instances, you could use the syntax offered by the protocol:

```python
app.services.register(Type, instance=some_instance)
```

But what I really recommend is to instantiate the DI container in a dedicated module, configure it outside of your application, and then instantiate the application this way:

```python
    app = Application(services=services)
```

The code that configures the DI container handles the specific type, which can be the Container class in `rodi` or any other class that works with alternative libraries for DI.

I considered doing the same for the `Router` class: the Application _might be_ refactored to only care about a router that can get a match by request object (method, path, headers). But I didn´t go down this path because of lack of time and because there are built-in features like `CORS` handling where an opinionated Router helps.
