### ISSUE TITLE
Support for background tasks

### ISSUE THREAD

**Issue by skivis** [Neoteroi/BlackSheep#81]
Not really an issue, more of a feature request I guess.

I'm wondering if you have thought about adding support for running background tasks in Blacksheep, similar to something like FastApi (Starlette) has.

Atm I'm using an `AsyncIOEventEmitter` (pyee) for running stuff in the background but the problem is obviously that it's not integrated with the DI container in any way.

What's your thoughts on this?

**Comment by RobertoPrevato** [comment]
Hi @skivis 
it didn't came to my mind to implement an abstraction layer to handle background tasks, because what asyncio offers looks already ideal to me. By _ideal_ here I mean, to the right level of abstraction.

I prepared an example to show how I would handle background tasks, including the activation of a service resolved by the CI container / provider:

```python
import asyncio
from datetime import datetime

from blacksheep.server import Application
from blacksheep.server.responses import text

app = Application()


@app.route("/")
def home():
    return text(f"Hello, World! {datetime.utcnow().isoformat()}")


def get_current_timestamp():
    return datetime.utcnow().isoformat()


class Foo:
    def __init__(self) -> None:
        pass


async def task_example(app: Application) -> None:
    # example background task, running once every second,
    # this example also shows how to activate a service using the CI container
    while True:
        print(get_current_timestamp())

        my_foo = app.service_provider.get(Foo)
        assert isinstance(my_foo, Foo)
        print("Foo id: ", id(my_foo))

        await asyncio.sleep(1)


async def configure_background_tasks(app):
    asyncio.get_event_loop().create_task(task_example(app))


app.on_start += configure_background_tasks


app.services.add_exact_scoped(Foo)

```

To summarize:
* define a callback for the `app.on_start` event - this is responsible of configuring background tasks
* using `asyncio.get_event_loop().create_task(...)` method to create background tasks running in the same event loop
* using `app.service_provider.get(DesiredType)` to activate services

Running this application with uvicorn works as expected: the background task runs once every second.

---
I could write a page about this on the documentation website.

Would you recommend something more for background tasks?

**Comment by skivis** [comment]
No I agree , the abstraction that asyncio provides is definitely enough :)

I think I just overcomplicated things in my head. My goal was simply to launch the background task in a route handler and then reply to the request at once which was easy enough with asyncio.create_task(). I think FastApi and Starlette have some additional stuff going on, like ensuring that the background tasks are run after the response has been sent back etc, but thats wasn't important in my case.

Thanks for the quick reply!

**Comment by RobertoPrevato** [comment]
Thanks for your feedback, I like hearing opinions and getting a different point of view on things. 😄 

Now I understand more the scenario you have in mind. You are describing the use case of [HTTP 202 Accepted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202) response code: you start an operation and return immediately a response without knowing the result of that operation.

Yes, in such case I would use `create_task()` from asyncio, or `run_in_executor` if the operation is I/O or CPU intensive [(ref.)](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor).

---

I'll keep this issue open because it's worth writing a piece of documentation to describe these situations.

**Comment by RobertoPrevato** [comment]
This has been documented -> https://www.neoteroi.dev/blacksheep/background-tasks/
