### ISSUE TITLE
Add testing section to docs

### ISSUE THREAD

**Issue by Bloodielie** [Neoteroi/BlackSheep#83]
It would be great to see the testing section in the documentation, especially would like to see service testing (di)

**Comment by RobertoPrevato** [comment]
Hi @Bloodielie,
Thanks for the recommendation, it is a good idea to add a section about testing in the documentation and I'll do it. I was planning to add actually a section describing how to develop locally, how to run the tests and debug the tests using Visual Studio Code (and maybe PyCharm).

However, I wouldn't go so much into detail to describe specific tests, because it would require a lot of time and I have limited time for BlackSheep. All tests are in the public source code, though, so anybody can read the tests in this repository.

The service binding part is tested mostly in [test_application.py](https://github.com/Neoteroi/BlackSheep/blob/master/tests/test_application.py#L3173) (I link an example), but you can find some other tests in other files related to binders and controllers.

The DI part, as you know since you opened an issue in the other repository, is implemented in a dedicated library. Most of the tests that demonstrate proper functioning of this library can be found in its repository (e.g. ability to resolve graphs of services, support for scoped/singleton/transient, factories, etc.).
I intentionally kept the web framework separated from the library for dependency injection, because the second can be used in other kinds of applications.
